arb-dir: ./l10n
template-arb-file: app_es.arb
output-dir: lib/l10n
synthetic-package: false
output-localization-file: app_localizations.dart
output-class: AppLocalizations
untranslated-messages-file: unstralated_messages.yaml
