name: technical_test_flutter_sr
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.24.1"

dependencies:
  dio: ^5.4.1
  equatable: ^2.0.5
  fpdart: ^1.1.0
  flutter:
    sdk: flutter
  fluttertoast: ^8.0.8
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  flutter_screenutil: ^5.9.0
  flutter_secure_storage: ^4.2.1
  go_router: ^13.2.4
  loader_overlay: ^4.0.0
  pretty_dio_logger: ^1.3.1
  riverpod_annotation: ^2.3.3
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7
  build_runner: ^2.4.9
  custom_lint: ^0.5.7

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
